version: '3.9'

services:
  front:
    container_name: frontend
    image: public.ecr.aws/i1s4s1t2/inz:latest
    #build: ./Frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
  postgis:
    container_name: postgis
    image: postgis/postgis:16-3.4-alpine
    stdin_open: true 
    tty: true        
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: inz_user
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./dbbackup/inzynierka_dump.sql:/inzynierka_dump.sql
    - ./dbbackup/restore.sh:/docker-entrypoint-initdb.d/restore.sh
  api:
    container_name: api
    image: public.ecr.aws/i1s4s1t2/inz-api:latest
    #build: ./Backend
    ports: 
      - "2137:8080"
    environment:
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: inz_user
    depends_on:
      - postgis
volumes:
    pgdata: {}