version: '3.9'

services:
  front:
    container_name: frontend
    build: ./Frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
  postgis:
    container_name: postgis
    image: postgis/postgis:16-3.4-alpine
    stdin_open: true 
    tty: true        
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./dbbackup/inzynierka_dump.sql:/inzynierka_dump.sql
    - ./dbbackup/restore.sh:/docker-entrypoint-initdb.d/restore.sh
  api:
    container_name: api
    build: ./Backend
    ports: 
      - "2137:8080"
    environment:
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
    depends_on:
      - postgis
volumes:
    pgdata: {}